CC=g++
LIBS=-lsfml-graphics -lsfml-window -lsfml-system
CFLAGS= -std=c++17
srcdir=./src/
outdir=./build/

default: 
	$(CC) $(CFLAGS) -o $(outdir)2048.app $(srcdir)Driver.cpp $(LIBS)
	cd $(outdir) && .$(outdir)2048.app
